<?php

namespace VaderLab\AclBundle\Repository;

/**
 * EntityRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class EntityRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
