<?php

namespace VaderLab\AclBundle\Repository;

/**
 * UserRelationRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRelationRepository extends \Doctrine\ORM\EntityRepository
{
}
